import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import weathImage from "../public/images/weather.jpg"
import { BsSearch } from 'react-icons/bs';

import { useState } from 'react'
import Weather from '@/components/Weather';
import Spinner from '@/components/Spinner';


export default function Home() {
  const [weather, setWeather] = useState("")
  const [city, setCity] = useState("")
   const [loading, setLoading] = useState(false)

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=metric&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`

  // const fetchWeather = (e) => {
  //   e.preventDefault()
  //   setLoading(true);
  //   axios.get(url)
  //     .then(response => {
  //       setWeather(response.data)

  //     }
  //     )
  //   setCity("")
  //   setLoading(false)
  // }

  const fetchWeather = async(e) => {
    e.preventDefault()
    try {
      setLoading(true)
      const res =await axios.get(url)
      setWeather(res.data)
      setLoading(false)
    } catch (err) {
     alert("City is Not Found, please Refresh the page")
    }
  }

  if (loading) {
    return <Spinner />
  } else {
    return (
      <>
        <Head>
          <title>Weather-Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* OverLay */}
        <div className="absolute top-0 bottom-0 left-0 right-0 bg-black/30 z-[1] " />
        {/* BackGround */}
        <Image src={weathImage} layout="fill" className='object-cover' alt='/weather' />
        {/* Form */}
        <div className='relative flex  justify-between items-center mt-4 max-w-[400px] w-full z-10 m-auto'>
          <form onSubmit={fetchWeather} autoComplete='off' className=' flex justify-between items-center p-2 rounded-2xl border border-white w-full' >
            <div>
              <input onChange={e => setCity(e.target.value)} value={city} type="text" className='text-1xlw-full p-1 text-white bg-transparent placeholder:text-white focus:outline-none border-none' placeholder='Search a city' />
            </div>
            <button onClick={fetchWeather}>
              <BsSearch size={20} className="text-white" />
            </button>
          </form>
        </div>
        {/* Weather */}
        {weather.main && <Weather data={weather} />}
      </>
    )
  }


}
